PREFIX hpc: <https://github.com/HPC-FAIR/HPC-Ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tableurl: <http://example.org/rodinia-nw-lassen.csv#>


CONSTRUCT {
  ?URI a hpc:record;
    hpc:inputDataSize ?InputData;
    hpc:kernel ?Kernel;
    hpc:array ?Data;
    hpc:id ?DataID;
    hpc:DRAMFreq ?DRAM Frequency;
} 
FROM <file:rodinia_3.1_cuda_nw_labelledData-lassen-plus-rowId.csv> 

WHERE {
  BIND (URI(CONCAT('http://example.org/rodinia-nw-lassen.csv/', ?No)) AS ?URI)
  BIND (xsd:integer(?numEmps) AS ?numEmployees)
  BIND (xsd:decimal(?raisedAmt) AS ?amount)
}
