PREFIX hpc: <https://github.com/HPC-FAIR/HPC-Ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tableurl: <http://example.org/rodinia-nw-lassen.csv#>


CONSTRUCT {
# using table URL +row id as the URI for each record
  ?URI a hpc:TableRow;
    hpc:inputDataSize ?InputDataInt;
    hpc:kernel ?Kernel;
    hpc:array ?Data;
    hpc:id ?DataID;
    hpc:DRAMFreq ?DRAMFrequencyDec;
    hpc:Cycle ?ElapsedCyclesDec;
    hpc:MemberOccupancy ?MemoryOccupancyPct;
} 
FROM <file:rodinia_3.1_cuda_nw_labelledData-lassen-plus-rowId.csv> 

WHERE {
 # combine table url and row Id as the URI
  BIND (URI(CONCAT('http://example.org/rodinia-nw-lassen.csv/', ?No)) AS ?URI)

# convert inputData to integer inputDataSize
  BIND (xsd:integer(?InputData) AS ?InputDataInt)

# convert dram freq to decimal
  BIND (xsd:decimal(?DRAMFrequency) AS ?DRAMFrequencyDec)

  BIND (xsd:decimal(?ElapsedCycles) AS ?ElapsedCyclesDec)

  BIND (xsd:decimal(?MemoryPercentage) AS ?MemoryOccupancyPct)
}
